name: "Flagship - Rollback a campaign"
 
on:
  delete:
    tags:
      - '**'

jobs:
  flagship:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env tag version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        
      - name: REST API get list of campaigns
        run: |
          curl --request GET \
            --url https://api.flagship.io/v1/accounts/${{ secrets.FS_ACCOUNT_ID }}/account_environments/${{ secrets.FS_ENV_ID }}/campaigns \
            --header 'Authorization: Bearer ${{ secrets.FS_TOKEN }}' \
            --header 'accept: application/json' \
            --header 'content-type: application/json' >> campaigns.json
          cat campaigns.json

      - name: Parse json campaigns to get id of campaigns where modification taf is present
        run: |
          echo "CAMPAIGN_ID=`jq -r '.items[] | select(.variation_groups[] .variations[] .modifications .value[] as $k | $k == \"1.1\") .id' campaigns.json | uniq -u`" >> $GITHUB_ENV

      - name: REST API pause campaign
        run: |
          curl --request PATCH \
            --url https://api.flagship.io/v1/accounts/${{ secrets.FS_ACCOUNT_ID }}/account_environments/${{ secrets.FS_ENV_ID }}/campaigns/${{ env.CAMPAIGN_ID }} \
            --header 'Authorization: Bearer ${{ secrets.FS_TOKEN }}' \
            --header 'accept: application/json' \
            --header 'content-type: application/json' \
            --data '
            {
                "state": "paused",
            }
            '
