name: "Flagship - Rollback a campaign"
 
on:
  delete:
    tags:
      - '**'

jobs:
  flagship:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ref - ${{ github.event.ref }}"

      - uses: actions/checkout@v2
        
      - name: REST API get list of campaigns
        run: |
          curl --request GET \
            --url https://api.flagship.io/v1/accounts/${{ secrets.FS_ACCOUNT_ID }}/account_environments/${{ secrets.FS_ENV_ID }}/campaigns?_max_per_page=9999 \
            --header 'Authorization: Bearer ${{ secrets.FS_TOKEN }}' \
            --header 'accept: application/json' \
            --header 'content-type: application/json' >> campaigns.json

      - name: Parse json campaigns to get id of campaigns where modification taf is present
        run: |
          echo "CAMPAIGN_ID=`jq -r '.items[] | select(.variation_groups[] .variations[] .modifications .value[] as $k | $k == \"${{ github.event.ref }}\") .id' campaigns.json | uniq -u`" >> $GITHUB_ENV

      - name: REST API pause campaign
        run: |
          curl --request PATCH \
            --url https://api.flagship.io/v1/accounts/${{ secrets.FS_ACCOUNT_ID }}/account_environments/${{ secrets.FS_ENV_ID }}/campaigns/${{ env.CAMPAIGN_ID }}/toggle \
            --header 'Authorization: Bearer ${{ secrets.FS_TOKEN }}' \
            --header 'accept: application/json' \
            --header 'content-type: application/json' \
            --data '
            {
                "state": "paused"
            }
            '
